"""initial

Revision ID: 829af4c2cd78
Revises: 
Create Date: 2026-07-18 20:21:40.692662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829af4c2cd78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
